concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "zerotogitlab"
  url = "https://gitlab.yasserelkhayati.com"
  clone_url = "https://192.168.31.239"
  id = 3
  token = "glrt-t3_5LxBESXjkSomnY3Lxsog"          ## it should be replaced with the generate token
  token_obtained_at = 2025-03-22T21:40:43Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    runtime = "sysbox-runc"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    extra_hosts = ["gitlab.yasserelkhayati.com:192.168.31.239"]
    disable_cache = false
    volumes = ["/cache","/etc/docker/certs.d:/etc/docker/certs.d"]
    shm_size = 0
    network_mtu = 0
